BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "ADMINISTRADOR" (
	"ID_ADMIN"	INT AUTO_INCREMENT,
	"NOME_ADMINISTRADOR"	VARCHAR(50) NOT NULL,
	"SENHA_ADMINISTRADOR"	VARCHAR(50) NOT NULL,
	PRIMARY KEY("ID_ADMIN")
);
CREATE TABLE IF NOT EXISTS "IMAGENS" (
	"ID_IMG"	INT AUTO_INCREMENT,
	"CAMINHO_IMG"	VARCHAR(150),
	PRIMARY KEY("ID_IMG")
);
CREATE TABLE IF NOT EXISTS "NOTICIAS" (
	"ID_NOTICIAS"	INT AUTO_INCREMENT,
	"TITULO"	VARCHAR(150) NOT NULL,
	"RESUMO"	VARCHAR(250) NOT NULL,
	"CONTEUDO"	TEXT NOT NULL,
	"URL_IMAGEM"	TEXT,
	"URL_VIDEO"	TEXT,
	"DATA"	DATETIME,
	"FK_ADMINISTRADOR_ID_ADMIN"	INT,
	PRIMARY KEY("ID_NOTICIAS"),
	CONSTRAINT "FK_NOTICAS_ADM" FOREIGN KEY("FK_ADMINISTRADOR_ID_ADMIN") REFERENCES ""
);
CREATE TABLE IF NOT EXISTS "NOTICIA_IMG_TEM" (
	"FK_NOTICIAS_ID_NOTICIAS"	INT,
	"FK_IMAGENS_ID_IMG"	INT,
	CONSTRAINT "FK_NOTICIA_TEM_IMG_2" FOREIGN KEY("FK_IMAGENS_ID_IMG") REFERENCES "",
	CONSTRAINT "FK_NOTICIA_TEM_IMG_1" FOREIGN KEY("FK_NOTICIAS_ID_NOTICIAS") REFERENCES "NOTICIAS"("ID_NOTICIAS")
);
COMMIT;
