-- 1. Tabela Administrador
CREATE TABLE IF NOT EXISTS "ADMINISTRADOR" (
	"ID_ADMIN" SERIAL PRIMARY KEY,
	"NOME_ADMINISTRADOR" VARCHAR(50) NOT NULL,
	"SENHA_ADMINISTRADOR" VARCHAR(50) NOT NULL
);

-- 2. Tabela Noticias
CREATE TABLE IF NOT EXISTS "NOTICIAS" (
	"ID_NOTICIAS" SERIAL PRIMARY KEY,
	"TITULO" VARCHAR(150) NOT NULL,
	"RESUMO" VARCHAR(250) NOT NULL,
	"CONTEUDO" TEXT NOT NULL,
	"URL_VIDEO" TEXT,
	"DATA" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	"FK_ADMINISTRADOR_ID_ADMIN" INT REFERENCES "ADMINISTRADOR"("ID_ADMIN") ON DELETE SET NULL,
	"IMAGENS" TEXT[] -- O Postgres aceita uma lista (array) de textos direto na linha!
);

-- Insere o administrador de teste
INSERT INTO "ADMINISTRADOR" ("NOME_ADMINISTRADOR", "SENHA_ADMINISTRADOR") 
VALUES ('admin', '1234')
ON CONFLICT DO NOTHING;